from calibrate_pro.application.actions import ActionRegistry

# fmt: off
EXPECTED_ACTION_IDS = {
    "application.exit", "window.hide_or_minimize", "window.show", "window.toggle_visibility",
    "navigation.dashboard", "navigation.calibrate", "navigation.verify", "navigation.profiles",
    "navigation.ddc", "navigation.settings", "help.about", "onboarding.complete",
    "diagnostics.folder.open", "diagnostics.bundle.preview", "diagnostics.bundle.create",
    "display.detect", "calibration.open_for_display", "panel_profile.dialog.open",
    "panel_profile.edid.select_display", "panel_profile.edid.create",
    "panel_profile.import.choose", "panel_profile.import",
    "display.restore_defaults", "profile.install", "display.hdr_status",
    "display.characterization.use_generic", "workflow.select_display",
    "calibration.method.sensorless", "calibration.method.measured", "calibration.method.hybrid",
    "calibration.target.gamut", "calibration.target.whitepoint", "calibration.target.custom_cct",
    "calibration.target.gamma", "calibration.target.hdr",
    "calibration.preset.srgb_web", "calibration.preset.rec709", "calibration.preset.dci_p3",
    "calibration.preset.hdr10", "calibration.preset.photography",
    "calibration.generate", "calibration.preview", "calibration.confirm_plan",
    "calibration.decline_plan", "fake_acceptance.apply", "calibration.all",
    "verification.sensorless", "verification.measured", "report.save",
    "export.active.cube", "export.active.3dlut", "export.active.png", "export.active.icc",
    "export.active.mpv", "export.active.obs",
    "profile.list.refresh", "profile.inspect", "profile.rename", "profile.generate_all",
    "profile.activate", "profile.export", "profile.delete", "patterns.open",
    "ddc.stage.brightness", "ddc.stage.contrast", "ddc.stage.red_gain",
    "ddc.stage.green_gain", "ddc.stage.blue_gain", "ddc.stage.red_black_level",
    "ddc.stage.green_black_level", "ddc.stage.blue_black_level",
    "ddc.unsupported.image_mode", "ddc.unsupported.color_preset", "ddc.unsupported.gamma",
    "ddc.unsupported.factory_color_reset", "ddc.read_current", "ddc.restore_defaults",
    "ddc.raw_read", "ddc.raw_write", "ddc.apply",
    "settings.default_target", "settings.lut_size", "settings.output_directory", "settings.hdr",
    "settings.startup", "settings.minimize_to_tray", "settings.oled_automation",
    "settings.per_app.enabled", "settings.per_app.rules", "settings.argyll_path",
    "settings.panel_profiles_path", "tray.switch_profile", "measurement.live.toggle",
}

EXPECTED_SURFACES_BY_ACTION = {
    "application.exit": {"menu.file.exit", "tray.exit"},
    "window.hide_or_minimize": {"shortcut.escape"},
    "window.show": {"tray.show"},
    "window.toggle_visibility": {"tray.icon.activate"},
    "navigation.dashboard": {"sidebar.dashboard", "menu.view.dashboard"},
    "navigation.calibrate": {"sidebar.calibrate", "menu.view.calibrate"},
    "navigation.verify": {"sidebar.verify", "menu.view.verify"},
    "navigation.profiles": {"sidebar.profiles", "menu.view.profiles"},
    "navigation.ddc": {"sidebar.ddc", "menu.view.ddc"},
    "navigation.settings": {"sidebar.settings", "menu.view.settings"},
    "help.about": {"menu.help.about"},
    "onboarding.complete": {"dialog.onboarding.get_started"},
    "diagnostics.folder.open": {"settings.diagnostics.open_folder"},
    "diagnostics.bundle.preview": {"settings.diagnostics.preview_bundle"},
    "diagnostics.bundle.create": {"settings.diagnostics.create_bundle"},
    "display.detect": {
        "dashboard.refresh", "menu.view.refresh", "menu.display.detect", "dialog.add_display.scan"
    },
    "calibration.open_for_display": {"dashboard.display_card.calibrate"},
    "panel_profile.dialog.open": {"dashboard.add_display"},
    "panel_profile.edid.select_display": {"dialog.add_display.edid.display"},
    "panel_profile.edid.create": {"dialog.add_display.edid.create"},
    "panel_profile.import.choose": {"dialog.add_display.import.choose"},
    "panel_profile.import": {"dialog.add_display.import.commit"},
    "display.restore_defaults": {"menu.display.restore_defaults", "tray.restore_defaults"},
    "profile.install": {"menu.display.install_profile"},
    "display.hdr_status": {"menu.tools.hdr_status"},
    "display.characterization.use_generic": {"dashboard.characterization.use_generic"},
    "workflow.select_display": {"calibrate.display", "verify.display", "ddc.display"},
    "calibration.method.sensorless": {"calibrate.method.sensorless"},
    "calibration.method.measured": {"calibrate.method.measured"},
    "calibration.method.hybrid": {"calibrate.method.hybrid"},
    "calibration.target.gamut": {"calibrate.target.gamut"},
    "calibration.target.whitepoint": {"calibrate.target.whitepoint"},
    "calibration.target.custom_cct": {"calibrate.target.custom_cct"},
    "calibration.target.gamma": {"calibrate.target.gamma"},
    "calibration.target.hdr": {"calibrate.target.hdr"},
    "calibration.preset.srgb_web": {"calibrate.preset.srgb_web"},
    "calibration.preset.rec709": {"calibrate.preset.rec709"},
    "calibration.preset.dci_p3": {"calibrate.preset.dci_p3"},
    "calibration.preset.hdr10": {"calibrate.preset.hdr10"},
    "calibration.preset.photography": {"calibrate.preset.photography"},
    "calibration.generate": {"calibrate.generate"},
    "calibration.preview": {"calibrate.preview"},
    "calibration.confirm_plan": {"dialog.plan.accept"},
    "calibration.decline_plan": {"dialog.plan.decline"},
    "fake_acceptance.apply": set(),
    "calibration.all": {"dashboard.calibrate_all", "menu.file.calibrate_all", "tray.calibrate_all"},
    "verification.sensorless": {"verify.run_sensorless"},
    "verification.measured": {"verify.run_measured"},
    "report.save": {"verify.export_report"},
    "export.active.cube": {"menu.export.cube"},
    "export.active.3dlut": {"menu.export.3dlut"},
    "export.active.png": {"menu.export.png"},
    "export.active.icc": {"menu.export.icc"},
    "export.active.mpv": {"menu.export.mpv"},
    "export.active.obs": {"menu.export.obs"},
    "profile.list.refresh": {"profiles.refresh"},
    "profile.inspect": {"profiles.card.inspect"},
    "profile.rename": {"profiles.rename"},
    "profile.generate_all": {"profiles.generate_all"},
    "profile.activate": {"profiles.card.activate"},
    "profile.export": {"profiles.card.export"},
    "profile.delete": {"profiles.card.delete"},
    "patterns.open": {"menu.tools.patterns"},
    "ddc.stage.brightness": {"ddc.brightness"},
    "ddc.stage.contrast": {"ddc.contrast"},
    "ddc.stage.red_gain": {"ddc.red_gain"},
    "ddc.stage.green_gain": {"ddc.green_gain"},
    "ddc.stage.blue_gain": {"ddc.blue_gain"},
    "ddc.stage.red_black_level": {"ddc.red_black_level"},
    "ddc.stage.green_black_level": {"ddc.green_black_level"},
    "ddc.stage.blue_black_level": {"ddc.blue_black_level"},
    "ddc.unsupported.image_mode": {"ddc.image_mode"},
    "ddc.unsupported.color_preset": {"ddc.color_preset"},
    "ddc.unsupported.gamma": {"ddc.gamma"},
    "ddc.unsupported.factory_color_reset": {"ddc.factory_color_reset"},
    "ddc.read_current": {"ddc.read_current"},
    "ddc.restore_defaults": {"ddc.restore_defaults"},
    "ddc.raw_read": {"ddc.raw_read"},
    "ddc.raw_write": {"ddc.raw_write"},
    "ddc.apply": {"ddc.apply"},
    "settings.default_target": {"settings.default_target"},
    "settings.lut_size": {"settings.lut_size"},
    "settings.output_directory": {"settings.output_directory", "settings.output_directory.browse"},
    "settings.hdr": {"settings.hdr"},
    "settings.startup": {"settings.startup"},
    "settings.minimize_to_tray": {"settings.minimize_to_tray"},
    "settings.oled_automation": {"settings.oled_automation"},
    "settings.per_app.enabled": {"settings.per_app.enabled"},
    "settings.per_app.rules": {
        "settings.per_app.table", "settings.per_app.add", "settings.per_app.remove",
        "settings.per_app.profile", "settings.per_app.action"
    },
    "settings.argyll_path": {"settings.argyll_path", "settings.argyll_path.browse"},
    "settings.panel_profiles_path": {"settings.panel_profiles_path", "settings.panel_profiles_path.browse"},
    "tray.switch_profile": {"tray.profile.dynamic"},
    "measurement.live.toggle": {"dashboard.live_sensor.toggle"},
}
# fmt: on


def test_default_registry_matches_complete_initial_action_census():
    registry = ActionRegistry.load_default()

    assert registry.action_ids == frozenset(EXPECTED_ACTION_IDS)
    assert registry.surfaces_by_action == {
        action_id: frozenset(surfaces) for action_id, surfaces in EXPECTED_SURFACES_BY_ACTION.items()
    }
